--- #YAML:1.0
name:                Data-PowerSet
version:             0.04
abstract:            Generate all subsets of a list of elements
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Landgren
