--- #YAML:1.0
name:                Data-PowerSet
version:             0.05
abstract:            Generate all subsets of a list of elements
license:             perl
author:              
    - David Landgren
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
